Modal rating toast
mehul-anand/delta-ui pull request #7
Opened 2022-02-19 15:46 UTC by mehul-anand

# Modal
# Rating
# Toast

2022-02-19 16:06 UTC, partha8 commented on docs.html
> +          <button class="btn-class">
suggestion: you can have better class names here. Instead of btn-div, have it as btn-container and instead of btn-class have it as btn. This way its easier to read your code.

2022-02-19 16:07 UTC, partha8 commented on docs.html
> +</iframe>  -->
please remove the comments.

2022-02-19 16:07 UTC, partha8 commented on rating.css
> +  direction: rtl;
Hey, this is new to me, can you please explain what it is?

2022-02-19 16:08 UTC, partha8 commented on toast.css
> +    height: 48px;
You can use rem here

2022-02-19 16:58 UTC, Developers-codz requested changes

2022-02-19 16:58 UTC, Developers-codz commented on modal.css
> +  /* border: none; */
remove commented code

2022-02-19 16:58 UTC, Developers-codz commented on toast.css
> +    width: 350px;
don't use PX if it has large value

2022-02-20 05:19 UTC, mehul-anand commented on modal.css
> +  /* border: none; */
I will remove the comments 
Thanks

2022-02-20 05:23 UTC, mehul-anand commented on rating.css
> +  direction: rtl;
rtl stands for right to left 
It is used to specify the direction of writing contents in a block
You can read more about them here :- 
[MDN](https://developer.mozilla.org/en-US/docs/Glossary/rtl)
[w3schools](https://www.w3schools.com/cssref/pr_text_direction.asp)

2022-02-20 05:23 UTC, mehul-anand commented on docs.html
> +</iframe>  -->
I will remove the comments 
Thanks

2022-02-20 05:23 UTC, mehul-anand commented on docs.html
> +          <button class="btn-class">
got it , I will make the changes

2022-02-20 05:23 UTC, mehul-anand commented on docs.html
> +          <button class="btn-class">
Thanks a lot for the review

2022-02-20 05:24 UTC, mehul-anand commented on toast.css
> +    height: 48px;
I will convert the values , thanks a lot

2022-02-20 05:24 UTC, mehul-anand commented on toast.css
> +    width: 350px;
gor it , I will convert px to rem , thanks a lot

2022-03-25 20:12 UTC, closed without merging